# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 530)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 450))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 900))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(600, 450))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 50, 601, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.chessboard = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.chessboard.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.chessboard.setContentsMargins(0, 0, 0, 0)
        self.chessboard.setSpacing(0)
        self.chessboard.setObjectName("chessboard")
        self.confirm = QtWidgets.QPushButton(self.centralwidget)
        self.confirm.setEnabled(False)
        self.confirm.setGeometry(QtCore.QRect(390, 380, 56, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirm.sizePolicy().hasHeightForWidth())
        self.confirm.setSizePolicy(sizePolicy)
        self.confirm.setObjectName("confirm")
        self.roundnumber = QtWidgets.QLabel(self.centralwidget)
        self.roundnumber.setGeometry(QtCore.QRect(50, 20, 51, 20))
        self.roundnumber.setObjectName("roundnumber")
        self.rounddisplay = QtWidgets.QLabel(self.centralwidget)
        self.rounddisplay.setGeometry(QtCore.QRect(100, 20, 41, 20))
        self.rounddisplay.setText("")
        self.rounddisplay.setObjectName("rounddisplay")
        self.up = QtWidgets.QPushButton(self.centralwidget)
        self.up.setEnabled(False)
        self.up.setGeometry(QtCore.QRect(170, 340, 41, 41))
        self.up.setObjectName("up")
        self.left = QtWidgets.QPushButton(self.centralwidget)
        self.left.setEnabled(False)
        self.left.setGeometry(QtCore.QRect(130, 380, 41, 41))
        self.left.setObjectName("left")
        self.right = QtWidgets.QPushButton(self.centralwidget)
        self.right.setEnabled(False)
        self.right.setGeometry(QtCore.QRect(210, 380, 41, 41))
        self.right.setObjectName("right")
        self.down = QtWidgets.QPushButton(self.centralwidget)
        self.down.setEnabled(False)
        self.down.setGeometry(QtCore.QRect(170, 420, 41, 41))
        self.down.setObjectName("down")
        self.statelabel = QtWidgets.QLabel(self.centralwidget)
        self.statelabel.setGeometry(QtCore.QRect(210, 10, 371, 41))
        self.statelabel.setText("")
        self.statelabel.setObjectName("statelabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 18))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.mode = QtWidgets.QMenu(self.menu)
        self.mode.setObjectName("mode")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.restart = QtWidgets.QAction(MainWindow)
        self.restart.setObjectName("restart")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.mode1 = QtWidgets.QAction(MainWindow)
        self.mode1.setObjectName("mode1")
        self.mode2 = QtWidgets.QAction(MainWindow)
        self.mode2.setEnabled(False)
        self.mode2.setObjectName("mode2")
        self.mode3 = QtWidgets.QAction(MainWindow)
        self.mode3.setEnabled(False)
        self.mode3.setObjectName("mode3")
        self.mode4 = QtWidgets.QAction(MainWindow)
        self.mode4.setEnabled(False)
        self.mode4.setObjectName("mode4")
        self.ai_set = QtWidgets.QAction(MainWindow)
        self.ai_set.setObjectName("ai_set")
        self.undo = QtWidgets.QAction(MainWindow)
        self.undo.setEnabled(False)
        self.undo.setObjectName("undo")
        self.save_current = QtWidgets.QAction(MainWindow)
        self.save_current.setEnabled(False)
        self.save_current.setObjectName("save_current")
        self.start = QtWidgets.QAction(MainWindow)
        self.start.setObjectName("start")
        self.action88 = QtWidgets.QAction(MainWindow)
        self.action88.setObjectName("action88")
        self.settings_2 = QtWidgets.QAction(MainWindow)
        self.settings_2.setObjectName("settings_2")
        self.settings = QtWidgets.QAction(MainWindow)
        self.settings.setObjectName("settings")
        self.match_settings = QtWidgets.QAction(MainWindow)
        self.match_settings.setObjectName("match_settings")
        self.loadfile = QtWidgets.QAction(MainWindow)
        self.loadfile.setEnabled(True)
        self.loadfile.setObjectName("loadfile")
        self.mode.addAction(self.mode1)
        self.mode.addAction(self.mode2)
        self.mode.addAction(self.mode3)
        self.mode.addAction(self.mode4)
        self.menu.addAction(self.mode.menuAction())
        self.menu.addAction(self.ai_set)
        self.menu.addSeparator()
        self.menu.addAction(self.match_settings)
        self.menu_2.addAction(self.start)
        self.menu_2.addAction(self.undo)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.save_current)
        self.menu_2.addAction(self.loadfile)
        self.menu_3.addAction(self.about)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "调试工具"))
        self.confirm.setText(_translate("MainWindow", "确定"))
        self.roundnumber.setText(_translate("MainWindow", "轮数"))
        self.up.setText(_translate("MainWindow", "上"))
        self.left.setText(_translate("MainWindow", "左"))
        self.right.setText(_translate("MainWindow", "右"))
        self.down.setText(_translate("MainWindow", "下"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.mode.setTitle(_translate("MainWindow", "模式"))
        self.menu_2.setTitle(_translate("MainWindow", "操作"))
        self.menu_3.setTitle(_translate("MainWindow", "帮助"))
        self.restart.setText(_translate("MainWindow", "重新开始"))
        self.action_2.setText(_translate("MainWindow", "重新开始"))
        self.about.setText(_translate("MainWindow", "说明"))
        self.mode1.setText(_translate("MainWindow", "电脑-电脑"))
        self.mode2.setText(_translate("MainWindow", "电脑-玩家"))
        self.mode3.setText(_translate("MainWindow", "玩家-电脑"))
        self.mode4.setText(_translate("MainWindow", "玩家-玩家"))
        self.ai_set.setText(_translate("MainWindow", "管理ai"))
        self.undo.setText(_translate("MainWindow", "撤销上一步移动"))
        self.undo.setShortcut(_translate("MainWindow", "Return"))
        self.save_current.setText(_translate("MainWindow", "保存当前对局记录"))
        self.start.setText(_translate("MainWindow", "开始"))
        self.action88.setText(_translate("MainWindow", "88"))
        self.settings_2.setText(_translate("MainWindow", "2"))
        self.settings.setText(_translate("MainWindow", "设置"))
        self.match_settings.setText(_translate("MainWindow", "设置"))
        self.match_settings.setIconText(_translate("MainWindow", "设置"))
        self.loadfile.setText(_translate("MainWindow", "读取记录"))
